apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adcapitaldb
  labels:
    app: adcapitaldb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: adcapitaldb
    spec:
      nodeSelector:
        node-role.kubernetes.io/compute: "true"
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: welcome1
        image: mysql:5.7
        name: adcapitaldb
        securityContext:
          privileged: true
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
