apiVersion: v1
kind: Service
metadata:
  labels:
    app: approval
  name: approval
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: approval
    environment: dev
status:
  loadBalancer: {}
