apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: approval
  labels:
    app: approval
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: approval
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: mysecret
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              key: accountname
              name: mysecret
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_AGENT_APPLICATION_NAME
              name: env-map
        - name: APPDYNAMICS_CONTROLLER_HOST_NAME
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_CONTROLLER_HOST_NAME
              name: env-map
        - name: APPDYNAMICS_CONTROLLER_PORT
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_CONTROLLER_PORT
              name: env-map
        - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_CONTROLLER_SSL_ENABLED
              name: env-map
        - name: APPD_AGENT_SHA256
          valueFrom:
            configMapKeyRef:
              key: APPD_AGENT_SHA256
              name: env-map
        - name: APPD_AGENT_VERSION
          valueFrom:
            configMapKeyRef:
              key: APPD_AGENT_VERSION
              name: env-map
        - name: APPD_DIR
          valueFrom:
            configMapKeyRef:
              key: APPD_DIR
              name: env-map
        - name: APPD_ES_HOST
          valueFrom:
            configMapKeyRef:
              key: APPD_ES_HOST
              name: env-map
        - name: APPD_ES_PORT
          valueFrom:
            configMapKeyRef:
              key: APPD_ES_PORT
              name: env-map
        - name: APPD_ES_SSL
          valueFrom:
            configMapKeyRef:
              key: APPD_ES_SSL
              name: env-map
        - name: APPD_EVENT_ACCOUNT_NAME
          valueFrom:
            configMapKeyRef:
              key: APPD_EVENT_ACCOUNT_NAME
              name: env-map
        - name: RETRY
          valueFrom:
            configMapKeyRef:
              key: RETRY
              name: env-map
        - name: TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: TIMEOUT
              name: env-map
        - name: ROLE
          value: approval
        - name: APPDYNAMICS_AGENT_NODE_NAME
          value: Approval
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: Approval-Services
        image: appddemo/adcapital-tomcat
        imagePullPolicy: Always
        name: approval
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          name: http-approval
        resources: {}
        volumeMounts:
        - mountPath: /project
          name: project
        - mountPath: /appdynamics
          name: appdynamics
      restartPolicy: Always
      volumes:
      - name: project
      - name: appdynamics
      initContainers:
        - image: appddemo/adcapital-project
          name: provider
          volumeMounts:
          - mountPath: /project
            name: project
status: {}
