apiVersion: v1
kind: Service
metadata:
  labels:
    app: load
  name: load
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: load
    environment: dev
status:
  loadBalancer: {}
