apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
  name: portal
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: portal
    environment: dev
status:
  loadBalancer: {}
