apiVersion: v1
kind: Service
metadata:
  labels:
    app: processor
  name: processor
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: processor
    environment: dev
status:
  loadBalancer: {}
