apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest
  name: rest
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: rest
    environment: dev
status:
  loadBalancer: {}
